import type { Match, MatchStage, MatchStatus, MatchWinner, Prediction, GroupStanding, RankingEntry } from './types'

// Helper para criar datas futuras
const getDateInDays = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

// Helper para criar datas passadas
const getDateInPast = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

export const MOCK_MATCHES: Match[] = [
  // Oitavas de Final - Próximos jogos
  {
    id: 'mock-1',
    _id: 'mock-1',
    externalId: '1',
    competition: 'Copa do Mundo 2026',
    stage: 'round_of_16' as MatchStage,
    roundLabel: 'Oitavas de Final',
    homeTeam: 'Brasil',
    homeTeamLogo: '🇧🇷',
    awayTeam: 'Argentina',
    awayTeamLogo: '🇦🇷',
    kickoffAt: getDateInDays(2),
    date: getDateInDays(2),
    teamA: 'Brasil',
    teamB: 'Argentina',
    status: 'scheduled' as MatchStatus,
    officialHomeScore: null,
    officialAwayScore: null,
    useManualScore: false,
    manualHomeScore: null,
    manualAwayScore: null,
    winner: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncedAt: new Date().toISOString(),
    canPredict: true,
  },
  {
    id: 'mock-2',
    _id: 'mock-2',
    externalId: '2',
    competition: 'Copa do Mundo 2026',
    stage: 'round_of_16' as MatchStage,
    roundLabel: 'Oitavas de Final',
    homeTeam: 'França',
    homeTeamLogo: '🇫🇷',
    awayTeam: 'Alemanha',
    awayTeamLogo: '🇩🇪',
    kickoffAt: getDateInDays(3),
    date: getDateInDays(3),
    teamA: 'França',
    teamB: 'Alemanha',
    status: 'scheduled' as MatchStatus,
    officialHomeScore: null,
    officialAwayScore: null,
    useManualScore: false,
    manualHomeScore: null,
    manualAwayScore: null,
    winner: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncedAt: new Date().toISOString(),
    canPredict: true,
  },
  {
    id: 'mock-3',
    _id: 'mock-3',
    externalId: '3',
    competition: 'Copa do Mundo 2026',
    stage: 'round_of_16' as MatchStage,
    roundLabel: 'Oitavas de Final',
    homeTeam: 'Espanha',
    homeTeamLogo: '🇪🇸',
    awayTeam: 'Inglaterra',
    awayTeamLogo: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    kickoffAt: getDateInDays(4),
    date: getDateInDays(4),
    teamA: 'Espanha',
    teamB: 'Inglaterra',
    status: 'scheduled' as MatchStatus,
    officialHomeScore: null,
    officialAwayScore: null,
    useManualScore: false,
    manualHomeScore: null,
    manualAwayScore: null,
    winner: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncedAt: new Date().toISOString(),
    canPredict: true,
  },
  {
    id: 'mock-4',
    _id: 'mock-4',
    externalId: '4',
    competition: 'Copa do Mundo 2026',
    stage: 'round_of_16' as MatchStage,
    roundLabel: 'Oitavas de Final',
    homeTeam: 'Portugal',
    homeTeamLogo: '🇵🇹',
    awayTeam: 'Itália',
    awayTeamLogo: '🇮🇹',
    kickoffAt: getDateInDays(5),
    date: getDateInDays(5),
    teamA: 'Portugal',
    teamB: 'Itália',
    status: 'scheduled' as MatchStatus,
    officialHomeScore: null,
    officialAwayScore: null,
    useManualScore: false,
    manualHomeScore: null,
    manualAwayScore: null,
    winner: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncedAt: new Date().toISOString(),
    canPredict: true,
  },
  // Jogos Finalizados
  {
    id: 'mock-5',
    _id: 'mock-5',
    externalId: '5',
    competition: 'Copa do Mundo 2026',
    stage: 'round_of_16' as MatchStage,
    roundLabel: 'Oitavas de Final',
    homeTeam: 'México',
    homeTeamLogo: '🇲🇽',
    awayTeam: 'Canadá',
    awayTeamLogo: '🇨🇦',
    kickoffAt: getDateInPast(2),
    date: getDateInPast(2),
    teamA: 'México',
    teamB: 'Canadá',
    status: 'finished' as MatchStatus,
    officialHomeScore: 2,
    officialAwayScore: 1,
    useManualScore: false,
    manualHomeScore: null,
    manualAwayScore: null,
    homeScore: 2,
    awayScore: 1,
    winner: 'home' as MatchWinner,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncedAt: new Date().toISOString(),
    canPredict: false,
  },
  {
    id: 'mock-6',
    _id: 'mock-6',
    externalId: '6',
    competition: 'Copa do Mundo 2026',
    stage: 'round_of_16' as MatchStage,
    roundLabel: 'Oitavas de Final',
    homeTeam: 'Holanda',
    homeTeamLogo: '🇳🇱',
    awayTeam: 'Bélgica',
    awayTeamLogo: '🇧🇪',
    kickoffAt: getDateInPast(1),
    date: getDateInPast(1),
    teamA: 'Holanda',
    teamB: 'Bélgica',
    status: 'finished' as MatchStatus,
    officialHomeScore: 3,
    officialAwayScore: 3,
    useManualScore: false,
    manualHomeScore: null,
    manualAwayScore: null,
    homeScore: 3,
    awayScore: 3,
    winner: 'draw' as MatchWinner,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncedAt: new Date().toISOString(),
    canPredict: false,
  },
]

export const MOCK_MY_PREDICTIONS: Prediction[] = [
  {
    id: 'pred-1',
    _id: 'pred-1',
    userId: 'user-1',
    matchId: 'mock-1',
    predictedHomeScore: 2,
    predictedAwayScore: 1,
    homeScore: 2,
    awayScore: 1,
    lockedAt: null,
    canEditUntil: getDateInDays(2),
    pointsAwarded: null,
    points: 0,
    exactScoreHit: false,
    outcomeHit: false,
    isExactScore: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Palpite que ganhou 1 ponto (acertou resultado)
  {
    id: 'pred-5',
    _id: 'pred-5',
    userId: 'user-1',
    matchId: 'mock-5',
    predictedHomeScore: 3,
    predictedAwayScore: 0,
    homeScore: 3,
    awayScore: 0,
    lockedAt: getDateInPast(2),
    canEditUntil: getDateInPast(2),
    pointsAwarded: 1,
    points: 1,
    exactScoreHit: false,
    outcomeHit: true,
    isExactScore: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Palpite que ganhou 2 pontos (placar exato)
  {
    id: 'pred-6',
    _id: 'pred-6',
    userId: 'user-1',
    matchId: 'mock-6',
    predictedHomeScore: 3,
    predictedAwayScore: 3,
    homeScore: 3,
    awayScore: 3,
    lockedAt: getDateInPast(1),
    canEditUntil: getDateInPast(1),
    pointsAwarded: 2,
    points: 2,
    exactScoreHit: true,
    outcomeHit: true,
    isExactScore: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_STANDINGS: GroupStanding[] = [
  {
    group: 'A',
    teams: [
      {
        team: 'Brasil',
        played: 3,
        won: 3,
        drawn: 0,
        lost: 0,
        goalsFor: 8,
        goalsAgainst: 2,
        goalDifference: 6,
        points: 9,
      },
      {
        team: 'Argentina',
        played: 3,
        won: 2,
        drawn: 0,
        lost: 1,
        goalsFor: 5,
        goalsAgainst: 3,
        goalDifference: 2,
        points: 6,
      },
      {
        team: 'Uruguai',
        played: 3,
        won: 1,
        drawn: 0,
        lost: 2,
        goalsFor: 3,
        goalsAgainst: 5,
        goalDifference: -2,
        points: 3,
      },
      {
        team: 'Chile',
        played: 3,
        won: 0,
        drawn: 0,
        lost: 3,
        goalsFor: 1,
        goalsAgainst: 7,
        goalDifference: -6,
        points: 0,
      },
    ],
    qualified: ['Brasil', 'Argentina'],
  },
  {
    group: 'B',
    teams: [
      {
        team: 'França',
        played: 3,
        won: 2,
        drawn: 1,
        lost: 0,
        goalsFor: 6,
        goalsAgainst: 2,
        goalDifference: 4,
        points: 7,
      },
      {
        team: 'Alemanha',
        played: 3,
        won: 2,
        drawn: 0,
        lost: 1,
        goalsFor: 5,
        goalsAgainst: 3,
        goalDifference: 2,
        points: 6,
      },
      {
        team: 'Holanda',
        played: 3,
        won: 1,
        drawn: 1,
        lost: 1,
        goalsFor: 4,
        goalsAgainst: 4,
        goalDifference: 0,
        points: 4,
      },
      {
        team: 'Bélgica',
        played: 3,
        won: 0,
        drawn: 0,
        lost: 3,
        goalsFor: 2,
        goalsAgainst: 8,
        goalDifference: -6,
        points: 0,
      },
    ],
    qualified: ['França', 'Alemanha'],
  },
]

export const MOCK_RANKING: RankingEntry[] = [
  {
    position: 1,
    userId: 'user-1',
    userName: 'João Silva',
    userEmail: 'joao@example.com',
    totalPoints: 150,
    exactScores: 10,
    outcomeHits: 25,
    totalPredictions: 35,
  },
  {
    position: 2,
    userId: 'user-2',
    userName: 'Maria Santos',
    userEmail: 'maria@example.com',
    totalPoints: 135,
    exactScores: 8,
    outcomeHits: 22,
    totalPredictions: 32,
  },
  {
    position: 3,
    userId: 'user-3',
    userName: 'Pedro Costa',
    userEmail: 'pedro@example.com',
    totalPoints: 120,
    exactScores: 7,
    outcomeHits: 20,
    totalPredictions: 28,
  },
  {
    position: 4,
    userId: 'user-4',
    userName: 'Ana Oliveira',
    userEmail: 'ana@example.com',
    totalPoints: 105,
    exactScores: 5,
    outcomeHits: 18,
    totalPredictions: 25,
  },
  {
    position: 5,
    userId: 'user-5',
    userName: 'Carlos Ferreira',
    userEmail: 'carlos@example.com',
    totalPoints: 95,
    exactScores: 4,
    outcomeHits: 16,
    totalPredictions: 22,
  },
]

export const MOCK_STATS = {
  totalMatches: 48,
  finishedMatches: 24,
  scheduledMatches: 24,
  totalPredictions: 580,
  totalUsers: 42,
  topScorer: {
    user: {
      id: 'user-1',
      name: 'João Silva',
      email: 'joao@example.com',
      role: 'user' as const,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    points: 150,
  },
  averagePointsPerUser: 85.5,
  mostPredictedMatch: {
    match: MOCK_MATCHES[0],
    predictionsCount: 38,
  },
}
